### ISSUE TITLE
Rucaptcha Timeout

### ISSUE THREAD

**Issue by Q0** [lorien/captcha_solver#5]
After 3-10 minutes of successful passes (5-10 Captchas) falls off with an error.
```
Traceback (most recent call last):
  File "C:\Users\Paul\AppData\Local\Programs\Python\Python36-32\lib\urllib\request.py", line 1318, in do_open
    encode_chunked=req.has_header('Transfer-encoding'))
  File "C:\Users\Paul\AppData\Local\Programs\Python\Python36-32\lib\http\client.py", line 1239, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "C:\Users\Paul\AppData\Local\Programs\Python\Python36-32\lib\http\client.py", line 1285, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "C:\Users\Paul\AppData\Local\Programs\Python\Python36-32\lib\http\client.py", line 1234, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "C:\Users\Paul\AppData\Local\Programs\Python\Python36-32\lib\http\client.py", line 1026, in _send_output
    self.send(msg)
  File "C:\Users\Paul\AppData\Local\Programs\Python\Python36-32\lib\http\client.py", line 964, in send
    self.connect()
  File "C:\Users\Paul\AppData\Local\Programs\Python\Python36-32\lib\http\client.py", line 936, in connect
    (self.host,self.port), self.timeout, self.source_address)
  File "C:\Users\Paul\AppData\Local\Programs\Python\Python36-32\lib\socket.py", line 722, in create_connection
    raise err
  File "C:\Users\Paul\AppData\Local\Programs\Python\Python36-32\lib\socket.py", line 713, in create_connection
    sock.connect(sa)
TimeoutError: [WinError 10060] Попытка установить соединение была безуспешной, т.к. от другого компьютера за требуемое время не получен нужный отклик, или было разорвано уже установленное соединение из-за неверного отклика уже подключенного компьютера

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:/Users/Paul/Dropbox/Projects/main.py", line 23, in rucaptcha_handler
    key = solver.solve_captcha(raw_data)
  File "C:\Users\Paul\AppData\Local\Programs\Python\Python36-32\lib\site-packages\captcha_solver\solver.py", line 73, in solve_captcha
    captcha_id = self.submit_captcha(image_data=data, **kwargs)
  File "C:\Users\Paul\AppData\Local\Programs\Python\Python36-32\lib\site-packages\captcha_solver\solver.py", line 53, in submit_captcha
    response = request(data['url'], data['post_data'])
  File "C:\Users\Paul\AppData\Local\Programs\Python\Python36-32\lib\site-packages\captcha_solver\network.py", line 13, in request
    response = urlopen(req)
  File "C:\Users\Paul\AppData\Local\Programs\Python\Python36-32\lib\urllib\request.py", line 223, in urlopen
    return opener.open(url, data, timeout)
  File "C:\Users\Paul\AppData\Local\Programs\Python\Python36-32\lib\urllib\request.py", line 526, in open
    response = self._open(req, data)
  File "C:\Users\Paul\AppData\Local\Programs\Python\Python36-32\lib\urllib\request.py", line 544, in _open
    '_open', req)
  File "C:\Users\Paul\AppData\Local\Programs\Python\Python36-32\lib\urllib\request.py", line 504, in _call_chain
    result = func(*args)
  File "C:\Users\Paul\AppData\Local\Programs\Python\Python36-32\lib\urllib\request.py", line 1346, in http_open
    return self.do_open(http.client.HTTPConnection, req)
  File "C:\Users\Paul\AppData\Local\Programs\Python\Python36-32\lib\urllib\request.py", line 1320, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [WinError 10060] Попытка установить соединение была безуспешной, т.к. от другого компьютера за требуемое время не получен нужный отклик, или было разорвано уже установленное соединение из-за неверного отклика уже подключенного компьютера>
```

**Code:**
```
def rucaptcha_handler(captcha):
    sleep(0.5)
    request = requests.get(str(captcha.get_url()), timeout=10, stream=True)
    with open('captcha.png', 'wb') as fh:
        for chunk in request.iter_content(1024 * 1024):
            fh.write(chunk)
    solver = CaptchaSolver('rucaptcha', api_key='key')
    raw_data = open('captcha.png', 'rb').read()
    key = solver.solve_captcha(raw_data)
    return captcha.try_again(key)
```

There are ideas how to solve?

**Comment by lorien** [comment]
Right now there is only one solution: wrap solve_captcha call into try/except, catch the URLError exception and handle it.

**Comment by Q0** [comment]
Yep, i'm doing that. But a problem, hmmm... Because the captcha is sent, it is solved, the money is withdrawn, but the answer does not come. Sometimes from 30 captchas can pass 15 fail. It's unclear why the connection breaks...

**Comment by lorien** [comment]
Try the captcha_solver from this branch: https://github.com/lorien/captcha_solver/tree/issue_5

It tries to re-send the network requests if it has been failed.

**Comment by Q0** [comment]
Thank you. Now works fine
